/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CicloJpaController;
import controller.MaestriaJpaController;
import controller.entityMan;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Ciclo;
import model.Maestria;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ricardo
 */
public class ReporteListaAlumnos extends javax.swing.JDialog {

    /**
     * Creates new form ReporteListaAlumnos
     */
    public ReporteListaAlumnos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarComboCiclo();
        llenarComboMaestria();
        llenarComboNroCiclo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbCiclo = new javax.swing.JComboBox();
        cbMaestria = new javax.swing.JComboBox();
        cbNroCiclo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        btnEstadoCuentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));

        jLabel1.setText("Semetre Academico: ");

        jLabel2.setText("Maestria :");

        jLabel3.setText("Ciclo:");

        jButton1.setText("Lista de Alumnos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Reporte de pagos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEstadoCuentas.setText("Estado de Cuentas");
        btnEstadoCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoCuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbCiclo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMaestria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNroCiclo, 0, 432, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btnEstadoCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMaestria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbNroCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btnEstadoCuentas))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "C:\\Users\\Ricardo\\Documents\\NetBeansProjects\\SistemasPagosPG\\src\\reportes\\report1.jasper";
        JasperReport jas = null;
        
        Maestria maestria = (Maestria) cbMaestria.getSelectedItem();
        Ciclo ciclo = (Ciclo) cbCiclo.getSelectedItem();
        Map mapa = new HashMap();
        mapa.put("nroCiclo",(Integer) cbNroCiclo.getSelectedItem());
        mapa.put("idMaestria",maestria.getIdMaestria());
        mapa.put("idCiclo", ciclo.getIdCiclo());
        
        try {
            jas = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint Jp = JasperFillManager.fillReport(jas,mapa ,AccesoDB.getConnection());
            JasperViewer jv = new JasperViewer(Jp);
            this.dispose();
            jv.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String path = "C:\\Users\\Ricardo\\Documents\\NetBeansProjects\\SistemasPagosPG\\src\\reportes\\report2.jasper";
        JasperReport jas = null;
        
        Maestria maestria = (Maestria) cbMaestria.getSelectedItem();
        Ciclo ciclo = (Ciclo) cbCiclo.getSelectedItem();
        Map mapa = new HashMap();
        mapa.put("nroCiclo",(Integer) cbNroCiclo.getSelectedItem());
        mapa.put("idMaestria",maestria.getIdMaestria());
        mapa.put("idCiclo", ciclo.getIdCiclo());
        
        try {
            jas = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint Jp = JasperFillManager.fillReport(jas,mapa ,AccesoDB.getConnection());
            JasperViewer jv = new JasperViewer(Jp);
            this.dispose();
            jv.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEstadoCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoCuentasActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
          String path = "C:\\Users\\Ricardo\\Documents\\NetBeansProjects\\SistemasPagosPG\\src\\reportes\\report4.jasper";
        JasperReport jas = null;
        Maestria maestria = (Maestria) cbMaestria.getSelectedItem();
        Ciclo ciclo = (Ciclo) cbCiclo.getSelectedItem();
        Map mapa = new HashMap();
        mapa.put("nroCiclo",(Integer) cbNroCiclo.getSelectedItem());
        mapa.put("idMaestria",maestria.getIdMaestria());
        mapa.put("idCiclo", ciclo.getIdCiclo());
        
        try {
            jas = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint Jp = JasperFillManager.fillReport(jas,mapa ,AccesoDB.getConnection());
            JasperViewer jv = new JasperViewer(Jp);
            this.dispose();
            jv.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_btnEstadoCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReporteListaAlumnos dialog = new ReporteListaAlumnos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadoCuentas;
    private javax.swing.JComboBox cbCiclo;
    private javax.swing.JComboBox cbMaestria;
    private javax.swing.JComboBox cbNroCiclo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void llenarComboCiclo() {
        CicloJpaController Cjc = new CicloJpaController(entityMan.getInstance());
        List<Ciclo> cicloJ = Cjc.findCicloEntities();
        cbCiclo.removeAllItems();
        for(Ciclo c : cicloJ){
          cbCiclo.addItem(c);
        }
    }
    private void llenarComboMaestria() {
        MaestriaJpaController Mjc = new MaestriaJpaController(entityMan.getInstance());
        List<Maestria> MaestriaL = Mjc.findMaestriaEntities();
        cbMaestria.removeAllItems();
        for(Maestria M : MaestriaL){
          cbMaestria.addItem(M);
        }
    }    

    private void llenarComboNroCiclo() {
        cbNroCiclo.addItem(1);
        cbNroCiclo.addItem(2);
        cbNroCiclo.addItem(3);
        cbNroCiclo.addItem(4);
        
    }
}
